### PR TITLE
Update values.yaml

### PR DESCRIPTION
**Pull request by mk-raven**
Use image tag from .Chart.AppVersion

### CODE REVIEW

**Comment by prune998** [comment]
Can you merge this ? 
What if I also add a `serviceAccount` ? This helm chart is less than pretty basic so far :) 
Anyone maintaining it ? Can I help ?

**Comment by lmangani** [comment]
@prune998 any help needs as we focus on the main application and the next major release.
I'd love to merge this but it has some conflicts that need to be resolved first :{

**Comment by prune998** [comment]
will check and update the PR then. thanks for quick reply

**Comment by lmangani** [comment]
Thank you for the kind offer to contribute @prune998 we appreciate it a ton!

**Pull request merged**
